apiVersion: apps/v1
kind: Deployment
metadata:
   name: static-website-deployment
spec:
  replicas: 2
  template:
    metadata:
      name: static-website
      labels:
        env: static-website
    spec:
      containers:
        - name: static-website
          image: anandgit71/qube-project:11.0.1
          imagePullPolicy: Always
  selector:
    matchLabels:
      env: static-website

---
apiVersion: v1
kind: Service
metadata:
  name: static-website-service
spec:
  ports:
    - targetPort: 80
      port: 80
      nodePort: 31009
  type: LoadBalancer
  selector:
    env: static-website

