---
- name: When_Condition example
  hosts: appgroup
  gather_facts: True

  tasks:
  - name: Apache installation
    yum: name=httpd state=absent
    when: ansible_distribution == 'CentOS' 

  - name: Apapche iNstallation on Ubuntu
    apt: name=apache2 state=latest
    when: ansible_distribution == 'Ubuntu'
