apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-rs
  namespace: dev
  labels:
    env: gateway-prod
spec:
  template:
    metadata:
      name: apache-pod
      labels:
        env: gateway-prod
    spec:
      containers:
        - name: apache-container
          image: httpd
          resources:
            requests:
              memory: "30Mi"
              cpu: "50m"
            limits:
              memory: "50Mi"
              cpu: "100m"
  replicas: 3
  selector:
    matchLabels:
      env: gateway-prod