apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    name: gateway-tech
    env: dev
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        name: gateway-tech
        env: dev
    spec:
      containers:
        - name: gateway-pod
          image: nginx
  replicas: 3
